name: build

on: push

jobs:
  build:
    runs-on: >-
      ${{
        (matrix.os == 'mac' && matrix.arch == 'arm64') &&
          'macos-14' ||
          (fromJson('{"linux":"ubuntu-22.04","mac":"macos-13","win":"windows-2022"}')[matrix.os])
      }}
    continue-on-error: false

    strategy:
      fail-fast: false
      matrix:
        os: [linux, mac]
        arch: [x64]
        include:
          - os: mac
            arch: arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build
        run: yarn && yarn build -p

      - name: Prepare .node file
        run: cp build/Release/executorch.node executorch-${{ matrix.os }}-${{ matrix.arch }}.node

      - name: Upload Binary Files
        uses: actions/upload-artifact@v4
        with:
          name: executorch-${{ matrix.os }}-${{ matrix.arch }}
          path: executorch-${{ matrix.os }}-${{ matrix.arch }}.node
          retention-days: 1

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      # Needed by action-gh-release.
      contents: write

    steps:
      - name: Download Files
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Compress files
        run: gzip *

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          name: executorch.js ${{ github.ref_name }}
          body: '## Changelog'
          files: '*.gz'
