name: npm-publish

on:
  release:
    types: [published]

jobs:
  post-release:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          # Required by npm publish.
          registry-url: https://registry.npmjs.org

      - name: Checkout
        uses: actions/checkout@v4

      - name: Get tag
        run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set package version
        run: |
          npm config set git-tag-version=false
          npm version $VERSION

      - name: Install deps
        run: yarn

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish
          npx dot-json package.json name @executorch/runtime
          npm publish --ignore-scripts --access public
          npx dot-json package.json name @executorch/runtime-cpu
          npm publish --ignore-scripts --access public
          npx dot-json package.json name @executorch/runtime-mps
          npm publish --ignore-scripts --access public
          npx dot-json package.json name @executorch/runtime-xnnpack
          npm publish --ignore-scripts --access public
